server:
  port: 10086
spring:
#  profiles: 20.48.5.1
  application:
    name: eureka-server
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    hostname: 20.48.5.1
#    prefer-ip-address: true
#    ip-address: 20.48.5.1

