server:
  port: 8081
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://20.48.5.5:4407/leyou
    username: root
    password: 123456

mybatis:
  type-aliases-package: cn.itcast.user.pojo
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10087/eureka,http://127.0.0.1:10088/eureka
  instance:
    hostname: 20.48.5.1
#    prefer-ip-address: true
#    ip-address: 20.48.5.1