server:
  port: 10086
spring:
  profiles: peer1
  application:
    name: eureka-server
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://20.48.5.1:10087/eureka,http://20.48.5.1:10088/eureka
  instance:
    hostname: 20.48.5.1
#    prefer-ip-address: true
#    ip-address: 20.48.5.1
---
server:
  port: 10087
spring:
  profiles: peer2
  application:
    name: eureka-server
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://20.48.5.1:10086/eureka,http://20.48.5.1:10088/eureka
  instance:
    hostname: 20.48.5.1
#    prefer-ip-address: true
#    ip-address: 20.48.5.1
---
server:
  port: 10088
spring:
  profiles: peer3
  application:
    name: eureka-server
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://20.48.5.1:10086/eureka,http://20.48.5.1:10087/eureka
  instance:
    hostname: 20.48.5.1
#    prefer-ip-address: true
#    ip-address: 20.48.5.1

