server:
  port: 8082
spring:
  application:
    name: consumer-service
eureka:
  client:
    service-url:
      defaultZone: http://20.48.5.1:10086/eureka,http://20.48.5.1:10087/eureka,http://20.48.5.1:10088/eureka
#    register-with-eureka: false
  instance:
    hostname: 20.48.5.1
#    prefer-ip-address: true
#    ip-address: 20.48.5.1

#user-service:
#  ribbon:
#    ReadTimeout: 3000
#    ConnectTimeout: 3000
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  eureka:
    enabled: true

feign:
  httpclient:
    connection-timeout: 50000
  client:
    config:
      remote-service:           #服务名，default为所有服务
        connectTimeout: 10000
        readTimeout: 60000
        loggerLevel: basic
      hystrix:
        enabled: true             #启用hystrix

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 10000
#
#    queryById:
#      execution.isolation.thread.timeoutInMilliseconds: 3000