server:
  port: 8082
spring:
  application:
    name: consumer-service
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    hostname: 20.48.5.1
#    prefer-ip-address: true
#    ip-address: 20.48.5.1